[package]
author = "Pooya Eimandar"
edition = "2021"
name = "wolf_stream"
version = "3.0.0"

[lib]
crate-type = ["rlib"]
name = "wolf_stream"
path = "src/lib.rs"

[dependencies]
# before adding any dependency please check it out from
# https://android.googlesource.com/platform/external/rust/crates/
anyhow = "1.0.51"
cxx = "1.0.57"
gstreamer-rtsp = "0.17.0"
gstreamer-rtsp-server = "0.17.2"
mimalloc = "0.1.27"
tokio = { version = "1.14.0", features = ["rt-multi-thread", "macros"] }

[build-dependencies]
cxx-build = "1.0.57"
git2 = "0.13.25"
plist = "1.3.1"
run_script = "0.9.0"

[features]
default = []
