[package]
categories = ["game-development", "game-engines", "games", "graphics", "multimedia"]
description = "Wolf is a set of modules for realtime rendering, realtime streaming and game developing"
edition = "2021"
keywords = ["gamedev", "system", "gamedev", "render"]
license = "Apache-2.0"
name = "wolfengine"
readme = "README.md"
repository = "https://github.com/WolfEngine/WolfEngine/"
version = "3.0.3"

[build]
rustc-link-lib = ["wolf_sys"]
rustc-link-search = ["sys/build/"]

[lib]
crate-type = ["rlib"]
name = "wolf"
path = "src/lib.rs"

# before adding any dependency please check it out from
# https://android.googlesource.com/platform/external/rust/crates/

# shared dependencies between all
[dependencies]
#brotli = { version = "3.3.3" }
anyhow = {version = "1.0.57", default-features = false}
signals2 = {version = "0.3.2", default-features = false}
raw-window-handle = {version = "0.4.3", default-features = false, features = ["alloc"]} 

# dependencies of wasm 
[target.'cfg(target_arch = "wasm32")'.dependencies]
instant = {version = "0.1.12", default-features = false, features = ["wasm-bindgen"]}
rhai = { version = "1.7.0", default-features = false, features = ["sync", "internals", "wasm-bindgen"], optional = true }
serde = { version = "1.0.137", default-features = false, features = ["derive"]}
wasm-bindgen = { version = "0.2.80", default-features = false }
wasm-bindgen-futures = { version = "0.4.30", default-features = false }
wasm-mt = {version = "0.1.2", default-features = false }
web-sys = {version = "0.3.57", default-features = false, features = ["console", "Document", "Window", "Element"]}
wgpu = {version = "0.12.0", default-features = false, features = ["webgl"], optional = true}

# shared dependencies between arm, aarch64 & x86_64
[target.'cfg(any(target_arch = "arm", target_arch = "aarch64", target_arch = "x86_64"))'.dependencies]
instant = {version = "0.1.12", default-features = false}
pollster = {version = "0.2.5", default-features = false}
rhai = { version = "1.7.0", default-features = false, features = ["sync", "internals"], optional = true}
rustls-pemfile = {version = "1.0.0", default-features = false}
tokio = {version = "1.18.2", default-features = false, features = ["full"]}
tokio-rustls = {version = "0.23.4", default-features = false, features = ["logging", "tls12"]}
tonic = {version = "0.7.2", default-features = false, features = ["codegen", "prost", "tls", "compression"], optional = true}
webpki-roots = {version = "0.22.3", default-features = false}
wgpu = {version = "0.12.0", default-features = false, optional = true}

# dependencies of arm, aarch64
# [target.'cfg(any(target_arch = "arm", target_arch = "aarch64"))'.dependencies]

# dependencies of x86_64
[target.'cfg(target_arch = "x86_64")'.dependencies]
# #scylla = {default-features = false, features = ["ssl"], version = "0.4.3"}
async-raft = {version = "0.6.1", default-features = false, optional = true}
async-trait = {version = "0.1.53", default-features = false}
futures = { version = "0.3.21", default-features = false }
hyper = {version = "0.14.18", default-features = false}
may = {version = "0.3.21", default-features = false}
memstore = {version = "0.2.0", default-features = false}
mimalloc = {version = "0.1.29", default-features = false, features = ["secure"]}
parking_lot = {version = "0.12.1",  default-features = false, features = ["deadlock_detection"]}
prost = {version = "0.10.3", default-features = false, optional = true}
serde_json = {version = "1.0.81", default-features = false, features = ["std"]}
sysinfo = {version = "0.23.12", default-features = false, features = ["multithread"]}
tracing = {version = "0.1.34", default-features = false, features = ["std", "attributes"]}
tokio-tungstenite = {version = "0.17.1", default-features = false, features = ["connect", "rustls"]}
uuid = {version = "1.0.0", default-features = false, features = ["v5"]}

[build-dependencies]
#bindgen = {version = "0.59.2"}
tonic-build = {version = "0.7.2", default-features = false, features = ["transport", "prost", "compression"]}

[dev-dependencies]
lazy_static = {version = "1.4.0", default-features = false}

# Wasm features
[features]
default = ["stream_rist"]
stream_grpc = ["tonic", "prost"] # enable gRPC (http2/1.1) for stream module
stream_rist = [] # enable RIST streaming protocol for stream module
system_lz4 = [] # enable LZ4 compression for system module
system_raft = ["async-raft", "prost"] # enable raft algorithm for system module
system_script = ["rhai"] # enable embedded script engine for system module
render = ["wgpu"]

# [[test]]
# name = "test_gametime"
# path = "tests/system_chrono.rs"
# required-features = ["default"]

# [[test]]
# name = "test_lz4"
# path = "tests/system_compression.rs"
# required-features = ["default", "system_lz4"]

# brotli = [] # enable brotli compression
# fiber = [] # enable fiber
# kafka_client = [] # enable Kafka client
# lzma = [] # enable LZMA Compression
# nng = [] # enable nng socket for tcp/udp/ipc protocols
# quic = [] # enable QUIC protocol
# redis_client = [] # enable redis client
# render = [] # enable real-time rendering
# rocksDB_client = [] # enable rocksDB client
# rtsp_client = [] # enable real time streaming protocol for client
# rtsp_server = [] # enable real time streaming protocol for server
# simd = [] # enable SIMD
# skyllaDB_client = [] # enable ScyllaDB client
# webRTC_client = [] # enable webRTC
# websocket_client = [] # enable websocket client
# websocket_server = [] # enable websocket server


