[package]
categories = ["game-development", "game-engines", "games", "graphics", "multimedia"]
description = "Wolf is a set of modules for realtime rendering, realtime streaming and game developing"
edition = "2021"
keywords = ["gamedev", "system", "gamedev", "render"]
license = "Apache-2.0"
name = "wolfengine"
readme = "README.md"
repository = "https://github.com/WolfEngine/WolfEngine/"
version = "3.0.2"

[lib]
crate-type = ["rlib", "cdylib"]
name = "wolf"
path = "src/lib.rs"

# before adding any dependency please check it out from
# https://android.googlesource.com/platform/external/rust/crates/

# Shared dependencies between Wasm & native
[dependencies]
#brotli = { version = "3.3.3" }
anyhow = {version = "1.0.56", default-features = false}
instant = {version = "0.1.12", default-features = false, features = ["wasm-bindgen"]}
wgpu = {version = "0.12.0", default-features = false, features = ["webgl"]}

# Wasm dependencies
#[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = {version = "0.1.7", default-features = false}
web-sys = {version = "0.3.56", default-features = false, features = ["console"]}
wasm-mt = {version = "0.1.2" }
serde = { version = "1.0.136", features = ["derive"] }
serde_closure = { version = "0.3.2" }
serde_traitobject = "0.2"
wasm-bindgen = { version = "0.2.79" }
wasm-bindgen-futures = { version = "0.4.29" }

# Native dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
#scylla = {default-features = false, features = ["ssl"], version = "0.4.3"}
async-raft = {version = "0.6.1", default-features = false}
async-trait = {version = "0.1.52", default-features = false}
hyper = {version = "0.14.18", default-features = false}
futures = {version = "0.3.21", default-features = false}
may = {default-features = false, version = "0.3.20"}
memstore = {default-features = false, version = "0.2.0"}
mimalloc = {default-features = false, features = ["secure"], version = "0.1.28"}
parking_lot = {default-features = false, features = ["deadlock_detection"], version = "0.12.0"}
pollster = {default-features = false, features = [], version = "0.2.5"}
prost = {default-features = false, version = "0.9.0"}
rustls-pemfile = {default-features = false, version = "0.3.0"}
serde_json = {default-features = false, features = ["std"], version = "1.0.79"}
sysinfo = {default-features = false, features = ["multithread"], version = "0.23.6"}
tokio = {default-features = false, features = ["full"], version = "1.17.0"}
tokio-rustls = {default-features = false, features = ["logging", "tls12"], version = "0.23.3"}
tokio-tungstenite = {default-features = false, features = ["connect", "rustls"], version = "0.17.1"}
tonic = {default-features = false, features = ["codegen", "prost", "tls", "compression"], version = "0.6.2"}
tracing = {default-features = false, features = ["std", "attributes"], version = "0.1.32"}
uuid = {default-features = false, features = ["v5"], version = "0.8.2"}
webpki-roots = {default-features = false, version = "0.22.2"}

[build-dependencies]
#bindgen = { version = "0.59.2" }
#vcpkg = {default-features = false, version = "0.2.15"}
tonic-build = {default-features = false, features = ["transport", "prost", "compression"], version = "0.6.2"}

[dev-dependencies]
lazy_static = {default-features = false, version = "1.4.0"}

[features]
default = ["system"]
system = []
render = []
stream = []
lua = []

