# [alias]

[build]
rustdocflags = [
  "-Dabsolute_paths_not_starting_with_crate",
  # "-Dbox_pointers", # TODO: We will consider it later
  "-Ddeprecated_in_future",
  # "-Delided_lifetimes_in_paths", # TODO: We have problem with cxx objects
  "-Dexplicit_outlives_requirements",
  "-Dkeyword_idents",
  "-Dmacro_use_extern_crate",
  "-Dmeta_variable_misuse",
  "-Dmissing_abi",
  # "-Dmissing_copy_implementations", # TODO: C++ copies object by default and Rust moves object by default, this feature should be optional based on developer's decision
  "-Dmissing_debug_implementations",
  # "-Dmissing_docs", # TODO: We will consider it later
  "-Dnon_ascii_idents",
  "-Dnoop_method_call",
  "-Dpointer_structural_match",
  # "-Drust_2021_incompatible_closure_captures", # TODO: Some deps did not compatible themslef with this feature yet. e.g Tonic
  "-Drust_2021_incompatible_or_patterns",
  "-Drust_2021_prefixes_incompatible_syntax",
  "-Drust_2021_prelude_collisions",
  "-Dsemicolon_in_expressions_from_macros",
  "-Dsingle_use_lifetimes",
  "-Dtrivial_casts",
  "-Dtrivial_numeric_casts",
  "-Dunreachable_pub",
  # "-Dunsafe_code", # TODO: We have to use unsafe codes (C/C++)
  # "-Dunsafe_op_in_unsafe_fn", # TODO: We have to use unsafe codes (C/C++)
  "-Dunstable_features",
  "-Dunused_crate_dependencies",
  "-Dunused_extern_crates",
  "-Dunused_import_braces",
  "-Dunused_lifetimes",
  "-Dunused_qualifications",
  "-Dunused_results",
  "-Dvariant_size_differences",
  "-Dwarnings"
]
rustflags = [
  "-Dabsolute_paths_not_starting_with_crate",
  # "-Dbox_pointers", # TODO: We will consider it later
  "-Ddeprecated_in_future",
  # "-Delided_lifetimes_in_paths", # TODO: We have problem with cxx objects
  "-Dexplicit_outlives_requirements",
  "-Dkeyword_idents",
  "-Dmacro_use_extern_crate",
  "-Dmeta_variable_misuse",
  "-Dmissing_abi",
  # "-Dmissing_copy_implementations", # TODO: C++ copies object by default and Rust moves object by default, this feature should be optional based on developer's decision
  "-Dmissing_debug_implementations",
  # "-Dmissing_docs", # TODO: We will consider it later
  "-Dnon_ascii_idents",
  "-Dnoop_method_call",
  "-Dpointer_structural_match",
  # "-Drust_2021_incompatible_closure_captures", # TODO: Some deps did not compatible themslef with this feature yet. e.g Tonic
  "-Drust_2021_incompatible_or_patterns",
  "-Drust_2021_prefixes_incompatible_syntax",
  "-Drust_2021_prelude_collisions",
  "-Dsemicolon_in_expressions_from_macros",
  "-Dsingle_use_lifetimes",
  "-Dtrivial_casts",
  "-Dtrivial_numeric_casts",
  "-Dunreachable_pub",
  # "-Dunsafe_code", # TODO: We have to use unsafe codes (C/C++)
  # "-Dunsafe_op_in_unsafe_fn", # TODO: We have to use unsafe codes (C/C++)
  "-Dunstable_features",
  "-Dunused_crate_dependencies",
  "-Dunused_extern_crates",
  "-Dunused_import_braces",
  "-Dunused_lifetimes",
  "-Dunused_qualifications",
  "-Dunused_results",
  "-Dvariant_size_differences",
  "-Dwarnings"
]

# [cargo-new]

# [http]

# [install]

# [net]

# [profile.<name>]

# [registries.<name>]

# [registry]

# [source.<name>]

# [target.<cfg>]

# [target.<triple>]

# [target.<triple>.<links>]

# [term]
